### ISSUE TITLE
Autodetect disk partitioning/type

### ISSUE THREAD

**Issue by danboid** [cloudbase/windows-openstack-imaging-tools#252]
The config.ini makes the user specify / choose between BIOS or UEFI disk partitioning so I presume this means you must create two separate images for each type of system, if you need to deploy Windows to machines of both types? Would it not be possible for this to be autodetected at install time, hence removing the need to specify one of the other in config.ini?

I have successfully created (I hope) my first image for MAAS using Windows 10 and UEFI. It is deploying now so hopefully it will work first time!? I couldn't find any complete docs on how to import the image into MAAS but I worked it out. I will upload a guide to the full process when I know its working.

**Comment by ader1990** [comment]
Hello,

Unfortunately, this is not how it works, to have one image that works both on UEFI and BIOS implementations, because the partitioning is different for each case -- which means you need different VHDs, thus two different images.

But most servers can implement UEFI booting plus fallback to the legacy boot, this might help in the case if you create only a BIOS supported image and want that to work on all your servers.

**Comment by danboid** [comment]
Ah right, I expected this would've already been implemented if easily done. I can set most of our machines to BIOS boot, as you say.

Thanks Adrian!
